/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface AsyncContent {
      /**
       * The path to the HTML content to be fetched
       */
      'src': string;
    }
  }

  interface HTMLAsyncContentElement extends StencilComponents.AsyncContent, HTMLStencilElement {}

  var HTMLAsyncContentElement: {
    prototype: HTMLAsyncContentElement;
    new (): HTMLAsyncContentElement;
  };
  interface HTMLElementTagNameMap {
    'async-content': HTMLAsyncContentElement;
  }
  interface ElementTagNameMap {
    'async-content': HTMLAsyncContentElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'async-content': JSXElements.AsyncContentAttributes;
    }
  }
  namespace JSXElements {
    export interface AsyncContentAttributes extends HTMLAttributes {
      /**
       * The path to the HTML content to be fetched
       */
      'src'?: string;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface AsyncError {
      /**
       * Clears the internal timer that determines when `<async-content />` should timeout. Called automatically as necessary by `<async-content />`
       */
      'cancel': () => void;
      /**
       * An optional function that should render when `<async-content>` encounters an error. The function is passed an object with `{ status, message }` in case you'd like either of those to be rendered.
       */
      'errorRender': (args: { status?: number, message?: string }) => JSX.Element;
      /**
       * A delay (in milliseconds) until the `<async-content>` fetch should be assumed to have timed out. Defaults to `10000`.
       */
      'ms': number;
      /**
       * Sets the Error status and message as passed to `errorRender` Called automatically by `<async-content />`
       */
      'setStatus': (status: number, message?: string) => void;
    }
  }

  interface HTMLAsyncErrorElement extends StencilComponents.AsyncError, HTMLStencilElement {}

  var HTMLAsyncErrorElement: {
    prototype: HTMLAsyncErrorElement;
    new (): HTMLAsyncErrorElement;
  };
  interface HTMLElementTagNameMap {
    'async-error': HTMLAsyncErrorElement;
  }
  interface ElementTagNameMap {
    'async-error': HTMLAsyncErrorElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'async-error': JSXElements.AsyncErrorAttributes;
    }
  }
  namespace JSXElements {
    export interface AsyncErrorAttributes extends HTMLAttributes {
      /**
       * An optional function that should render when `<async-content>` encounters an error. The function is passed an object with `{ status, message }` in case you'd like either of those to be rendered.
       */
      'errorRender'?: (args: { status?: number, message?: string }) => JSX.Element;
      /**
       * A delay (in milliseconds) until the `<async-content>` fetch should be assumed to have timed out. Defaults to `10000`.
       */
      'ms'?: number;
      /**
       * Emitted once `this.ms` has passed and the `<async-content>` fetch should be assumed to have timed out
       */
      'onHasError'?: (event: CustomEvent<void>) => void;
    }
  }
}


declare global {

  namespace StencilComponents {
    interface AsyncPlaceholder {
      /**
       * Clears the internal timer that determines when to display the placeholder. Called automatically as necessary by `<async-content/>`
       */
      'cancel': () => void;
      /**
       * An HTML tag that should be rendered as a placeholder.
       */
      'component': string;
      /**
       * Optionally, allows you to pass props to the placeholder component.
       */
      'componentProps': { [key: string]: any };
      /**
       * A delay (in milliseconds) until the placeholder should be shown. Defaults to `600`.
       */
      'ms': number;
    }
  }

  interface HTMLAsyncPlaceholderElement extends StencilComponents.AsyncPlaceholder, HTMLStencilElement {}

  var HTMLAsyncPlaceholderElement: {
    prototype: HTMLAsyncPlaceholderElement;
    new (): HTMLAsyncPlaceholderElement;
  };
  interface HTMLElementTagNameMap {
    'async-placeholder': HTMLAsyncPlaceholderElement;
  }
  interface ElementTagNameMap {
    'async-placeholder': HTMLAsyncPlaceholderElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'async-placeholder': JSXElements.AsyncPlaceholderAttributes;
    }
  }
  namespace JSXElements {
    export interface AsyncPlaceholderAttributes extends HTMLAttributes {
      /**
       * An HTML tag that should be rendered as a placeholder.
       */
      'component'?: string;
      /**
       * Optionally, allows you to pass props to the placeholder component.
       */
      'componentProps'?: { [key: string]: any };
      /**
       * A delay (in milliseconds) until the placeholder should be shown. Defaults to `600`.
       */
      'ms'?: number;
      /**
       * Emitted once `this.ms` has passed and the placeholder should be displayed
       */
      'onHasPlaceholder'?: (event: CustomEvent<void>) => void;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;