/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import '@smore/async-content';


declare global {

  namespace StencilComponents {
    interface AppRoot {

    }
  }

  interface HTMLAppRootElement extends StencilComponents.AppRoot, HTMLStencilElement {}

  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };
  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement;
  }
  interface ElementTagNameMap {
    'app-root': HTMLAppRootElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'app-root': JSXElements.AppRootAttributes;
    }
  }
  namespace JSXElements {
    export interface AppRootAttributes extends HTMLAttributes {

    }
  }
}


declare global {

  namespace StencilComponents {
    interface ExampleBasic {

    }
  }

  interface HTMLExampleBasicElement extends StencilComponents.ExampleBasic, HTMLStencilElement {}

  var HTMLExampleBasicElement: {
    prototype: HTMLExampleBasicElement;
    new (): HTMLExampleBasicElement;
  };
  interface HTMLElementTagNameMap {
    'example-basic': HTMLExampleBasicElement;
  }
  interface ElementTagNameMap {
    'example-basic': HTMLExampleBasicElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'example-basic': JSXElements.ExampleBasicAttributes;
    }
  }
  namespace JSXElements {
    export interface ExampleBasicAttributes extends HTMLAttributes {

    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
